name: CI MercaMax Frontend

on:
  push:
    branches: [main]

jobs:
  build:
    name: Verificar build Angular
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Build Angular
        run: npm run build --prod
